name: JobBoard
version: '${version}'
authors: [refractored]
main: net.refractored.jobboard.JobBoard
api-version: '1.20'
dependencies:
  server:
    eco:
      load: BEFORE
      required: true
      join-classpath: true